# Netlify Configuration File

[build]
  # Build komutu
  command = "npm run build"
  
  # Build çıktı klasörü
  publish = "dist"
  
  # Node versiyonu
  environment = { NODE_VERSION = "18" }

# Redirect rules - SPA için
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers - Security ve Performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# APK file headers
[[headers]]
  for = "/*.apk"
  [headers.values]
    Content-Type = "application/vnd.android.package-archive"
    Content-Disposition = "attachment"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cyberpunk versiyonu için de redirect
[[redirects]]
  from = "/cyberpunk"
  to = "/index-cyberpunk.html"
  status = 200
